USE bc_health; 


-- city-to-healath-authority mapping  data from : https://www.doctorsofbc.ca/about-us/who-we-are/governance/representative-assembly-districts-health-authorities
CREATE TABLE health_authority_lookup (
    city VARCHAR(200) PRIMARY KEY,
    health_authority VARCHAR(100)
);

INSERT INTO health_authority_lookup (city, health_authority) VALUES
('100 Mile House','Interior Health'),
('Abbotsford','Fraser Health'),
('Alert Bay','Island Health'),
('Anmore','Fraser Health'),
('Armstrong','Interior Health'),
('Ashcroft','Interior Health'),
('Barriere','Interior Health'),
('Belcarra','Fraser Health'),
('Bowen Island','Vancouver Coastal Health'),
('Burnaby','Fraser Health'),
('Burns Lake','Northern Health'),
('Cache Creek','Interior Health'),
('Campbell River','Island Health'),
('Castlegar','Interior Health'),
('Central Saanich','Island Health'),
('Chase','Interior Health'),
('Chetwynd','Northern Health'),
('Chilliwack','Fraser Health'),
('Clearwater','Interior Health'),
('Clinton','Interior Health'),
('Coldstream','Interior Health'),
('Colwood','Island Health'),
('Comox','Island Health'),
('Coquitlam','Fraser Health'),
('Courtenay','Island Health'),
('Cranbrook','Interior Health'),
('Creston','Interior Health'),
('Dawson Creek','Northern Health'),
('Delta','Fraser Health'),
('Duncan','Island Health'),
('Elkford','Interior Health'),
('Enderby','Interior Health'),
('Esquimalt','Island Health'),
('Fernie','Interior Health'),
('Fort St. James','Northern Health'),
('Fort St. John','Northern Health'),
('Fraser Lake','Northern Health'),
('Fruitvale','Interior Health'),
('Gibsons','Vancouver Coastal Health'),
('Gold River','Island Health'),
('Golden','Interior Health'),
('Grand Forks','Interior Health'),
('Granisle','Northern Health'),
('Greenwood','Interior Health'),
('Harrison Hot Springs','Fraser Health'),
('Hazelton','Northern Health'),
('Highlands','Island Health'),
('Hope','Fraser Health'),
('Houston','Northern Health'),
('Hudson''s Hope','Northern Health'),
('Invermere','Interior Health'),
('Kamloops','Interior Health'),
('Kaslo','Interior Health'),
('Kelowna','Interior Health'),
('Kent','Fraser Health'),
('Keremeos','Interior Health'),
('Kimberley','Interior Health'),
('Kitimat','Northern Health'),
('Ladysmith','Island Health'),
('Lake Country','Interior Health'),
('Lake Cowichan','Island Health'),
('Langford','Island Health'),
('Langley, City of','Fraser Health'),
('Langley, District Municipality','Fraser Health'),
('Lillooet','Interior Health'),
('Lions Bay','Vancouver Coastal Health'),
('Logan Lake','Interior Health'),
('Lumby','Interior Health'),
('Lytton','Interior Health'),
('Mackenzie','Northern Health'),
('Maple Ridge','Fraser Health'),
('Masset','Northern Health'),
('McBride','Northern Health'),
('Merritt','Interior Health'),
('Metchosin','Island Health'),
('Midway','Interior Health'),
('Mission','Fraser Health'),
('Montrose','Interior Health'),
('Nakusp','Interior Health'),
('Nanaimo','Island Health'),
('Nelson','Interior Health'),
('New Denver','Interior Health'),
('New Westminster','Fraser Health'),
('North Cowichan','Island Health'),
('North Saanich','Island Health'),
('North Vancouver, City of','Vancouver Coastal Health'),
('North Vancouver, District Municipality','Vancouver Coastal Health'),
('Oak Bay','Island Health'),
('Oliver','Interior Health'),
('Osoyoos','Interior Health'),
('Parksville','Island Health'),
('Peachland','Interior Health'),
('Pemberton','Vancouver Coastal Health'),
('Penticton','Interior Health'),
('Pitt Meadows','Fraser Health'),
('Port Alberni','Island Health'),
('Port Alice','Island Health'),
('Port Coquitlam','Fraser Health'),
('Port Hardy','Island Health'),
('Port McNeill','Island Health'),
('Port Moody','Fraser Health'),
('Powell River','Vancouver Coastal Health'),
('Prince George','Northern Health'),
('Prince Rupert','Northern Health'),
('Princeton','Interior Health'),
('Qualicum Beach','Island Health'),
('Quesnel','Northern Health'),
('Radium Hot Springs','Interior Health'),
('Revelstoke','Interior Health'),
('Richmond','Vancouver Coastal Health'),
('Rossland','Interior Health'),
('Saanich','Island Health'),
('Salmo','Interior Health'),
('Salmon Arm','Interior Health'),
('Sechelt District Municipality','Vancouver Coastal Health'),
('Sicamous','Interior Health'),
('Sidney','Island Health'),
('Silverton','Interior Health'),
('Slocan','Interior Health'),
('Smithers','Northern Health'),
('Sooke','Island Health'),
('Spallumcheen','Interior Health'),
('Sparwood','Interior Health'),
('Squamish','Vancouver Coastal Health'),
('Stewart','Northern Health'),
('Summerland','Interior Health'),
('Sun Peaks Mountain','Interior Health'),
('Surrey','Fraser Health'),
('Tahsis','Island Health'),
('Taylor','Northern Health'),
('Terrace','Northern Health'),
('Tofino','Island Health'),
('Trail','Interior Health'),
('Tumbler Ridge','Northern Health'),
('Ucluelet','Island Health'),
('Valemount','Northern Health'),
('Vancouver','Vancouver Coastal Health'),
('Vanderhoof','Northern Health'),
('Vernon','Interior Health'),
('Victoria','Island Health'),
('View Royal','Island Health'),
('Warfield','Interior Health'),
('West Kelowna','Interior Health'),
('West Vancouver','Vancouver Coastal Health'),
('Whistler','Vancouver Coastal Health'),
('White Rock','Fraser Health'),
('Williams Lake','Interior Health'),
('Wells','Interior Health'),
('Zeballos','Island Health'),
('Cumberland','Island Health'),
('Lantzville','Island Health'),
('Northern Rockies Regional Municipality','Northern Health'),
('Telkwa','Northern Health'),
('Daajing Giids','Northern Health'),
('Canal Flats','Interior Health'),
('Pouce Coupe','Northern Health'),
('sh?sh lh Nation Gov Dist (Part-Sunshine Coast)','Vancouver Coastal Health'),
('New Hazelton','Northern Health'),
('Port Edward','Northern Health'),
('Port Clements','Northern Health'),
('Sayward','Island Health'),
('sh?sh lh Nation Gov Dist (Part-qathet)','Vancouver Coastal Health');

SELECT *
FROM health_authority_lookup
;

